USERS = {
    "ADMIN": "admin",
    "COACH": "coach",
    "PLAYER": "player"
}

ERROR_CODES = {
    "COACH_EMAIL_IS_ALREADY_IN_USE": 3000,
    "COACH_USERNAME_IS_ALREADY_IN_USE": 3001,
    "FAILED_TO_REGISTER_COACH": 3002,

    "PLAYER_EMAIL_IS_ALREADY_IN_USE": 3003,
    "PLAYER_USERNAME_IS_ALREADY_IN_USE": 3004,
    "FAILED_TO_REGISTER_PLAYER": 3005,

    "COACH_ALREADY_HAS_A_TEAM": 3006,
    "FAILED_TO_CREATE_TEAM": 3007,

    "INVALID_PLAYER_COUNT": 3008,
    "PLAYER_ALREADY_ASSIGNED": 3009,
    "FAILED_TO_JOIN": 3010,

    "FAILED_TO_CREATE_GAME": 3011,
    "INVALID_USER_UPDATE_PERMISSION": 3012,
    "FAILED_TO_UPDATE_GAME_COUNT": 3013,
    "FAILED_TO_UPDATE_TEAM_SCORE": 3014,
    "FAILED_TO_UPDATE_AVG_TEAM_SCORE": 3015,
    "FAILED_TO_UPDATE_AVG_PLAYER_SCORE": 3016,
    "FAILED_TO_REMOVE_PLAYER": 3017,
}